# Generated by Django 3.2.14 on 2022-10-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ritmos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipos_de_baile',
            name='imagen',
        ),
    ]
