# Generated by Django 3.2.14 on 2022-10-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritmos', '0002_remove_tipos_de_baile_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('mensaje', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tipos_de_baile',
            options={'verbose_name': 'Tipo de baile', 'verbose_name_plural': 'Tipos de bailes'},
        ),
    ]
