# Generated by Django 3.2.14 on 2022-10-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritmos', '0003_auto_20221027_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_de_baile',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Ritmos'),
        ),
    ]
